Tests
deciever5/dingo pull request #1
Opened 2023-03-15 09:20 UTC by deciever5

Database updates with posts and authors. Instances of both added.

2023-03-16 09:51 UTC, MarekBiczysko requested changes

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/migrations/0002_rename_author_id_post_author.py
> +    ]
zamiast tworzyć nową migrację możemy zmodyfikować 0001_initial

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/models.py
> +    author = models.ForeignKey('posts.Author', on_delete=models.CASCADE, null=True)
pole author powinno być nienullowalne

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/models.py
> +    content = models.TextField()
Zastanów się jak można zlimitować także ilość znaków (np do 1024) dla TextField, sprawdź także jaką maksymalną ilość znaków można zapisać defaultowo w TextField i jakie może rodzić to problemy

https://docs.djangoproject.com/en/4.1/ref/models/fields/#textfield
https://docs.djangoproject.com/en/3.2/ref/models/instances/#validating-objects

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/models.py
> +    modified = models.DateTimeField(auto_now_add=True)
To jest bardzo częsty pattern używany w modelach, więc powszechnym rozwiązaniem jest używanie TimeStampModel z appki https://github.com/django-extensions/django-extensions, spróbuj dodać ją do projektu i zobaczyć jak działa dziedziczenie po TimeStampModel (abstract=True)

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/models.py
> +    bio = models.TextField(blank=True, null=True)
Tworzenie pól tekstowych z blank=True i null=True to bad pattern, gdyż pozwala na 2 rózne sposoby zapisania "pustej" wartosci, do poczytania https://simpleisbetterthancomplex.com/tips/2016/07/25/django-tip-8-blank-or-null.html

2023-03-16 09:51 UTC, MarekBiczysko commented on posts/models.py
> +    email = models.EmailField(max_length=30, blank=True, null=True)
Zadanie tego nie definiuje wprost, ale zróbmy to pole także unikalnym

2023-03-16 18:02 UTC, MarekBiczysko commented on posts/models.py
> +    content = models.TextField()
manage.py shell_plus

2023-03-16 18:03 UTC, MarekBiczysko commented on posts/models.py
> +    content = models.TextField()
nadpisanie save()

2023-03-16 18:04 UTC, MarekBiczysko commented on posts/models.py
> +    modified = models.DateTimeField(auto_now_add=True)
Post(TimestampModel)

2023-03-16 18:06 UTC, MarekBiczysko commented on posts/models.py
> +    bio = models.TextField(blank=True, null=True)
None, ""
Post.objects.exclude(bio__isnull=True, bio="")

2023-03-20 11:37 UTC, deciever5 commented on posts/migrations/0002_rename_author_id_post_author.py
> +    ]
merged

2023-03-20 12:18 UTC, deciever5 commented on posts/models.py
> +    content = models.TextField()
save method updated

2023-03-27 10:49 UTC, closed without merging